WebAppLayer/Controllers/CategoryController.cs
using Microsoft.AspNetCore.Mvc;
using Entities;
using Microsoft.AspNetCore.Authorization;
using ProxyServiceLayer;
using WebAppLayer.Models;

namespace WebAppLayer.Controllers;

[Authorize]
public class CategoryController : Controller
{
    private readonly CategoryViewModel _CategoryViewModel;

    public CategoryController()
    {
        _CategoryViewModel = new CategoryViewModel();
    }

    // Acción GET: Los roles 'Client', 'Employee' y 'Admin' tienen acceso
    [HttpGet]
    public IActionResult Index()
    {
        // No necesitas validar los roles aquí porque todos los usuarios autenticados tienen acceso.
        var CategoryProxy = new CategoryProxy();
        var Categories = CategoryProxy.GetCategories();
        _CategoryViewModel.Categories = Categories;
        return View(_CategoryViewModel);
    }

    // Acción POST: Solo los roles 'Admin' y 'Employee' pueden agregar Categoryos
    [Authorize(Roles = "Admin,Employee")]
    [HttpPost]
    [ValidateAntiForgeryToken]
    public IActionResult Create(Category Category)
    {
        var CategoryProxy = new CategoryProxy();
        var result = CategoryProxy.Create(Category);
        _CategoryViewModel.Error = result == null ? "Categoryo no pudo ser guardado" : "";
        return RedirectToAction("Index");
    }

    // Acción GET: Solo los roles 'Admin' y 'Employee' pueden gestionar Categoryos

    [HttpGet]
    public IActionResult Search(int CategoryId)
    {
        var CategoryProxy = new CategoryProxy();
        var CategoryFound = CategoryProxy.RetrieveById(CategoryId);
        _CategoryViewModel.Categories = CategoryProxy.GetCategories();
        _CategoryViewModel.CategorySearch = CategoryFound; // Asignar el Category encontrado
        _CategoryViewModel.Error = CategoryFound == null ? "Category not found" : ""; // Error si el Categoryo no se encuentra

        return View("Index", _CategoryViewModel); // Pasar el modelo a la vista
    }

    [HttpGet]
    [Authorize(Roles = "Admin,Employee")]
    public IActionResult Delete(int id)
    {
        var CategoryProxy = new CategoryProxy();
        bool isDeleted = CategoryProxy.Delete(id);
        _CategoryViewModel.Error = isDeleted ? "" : "Category cannot be deleted";

        return RedirectToAction("Index");
    }
    
    [HttpPost]
    [ValidateAntiForgeryToken]
    [Authorize(Roles = "Admin,Employee")]
    public IActionResult Update(Category Category) {
        var CategoryProxy = new CategoryProxy();
        bool isUpdated = CategoryProxy.Update(Category);
        _CategoryViewModel.Error = isUpdated ? "" : "Category cannot be updated";

        return RedirectToAction("Index");
    }
}

WebAppLayer/Controllers/ProductController.cs
using Microsoft.AspNetCore.Mvc;
using Entities;
using Microsoft.AspNetCore.Authorization;
using ProxyServiceLayer;
using WebAppLayer.Models;

namespace WebAppLayer.Controllers;

[Authorize]
public class ProductController : Controller
{
    private readonly ProductViewModel _productViewModel;

    public ProductController()
    {
        _productViewModel = new ProductViewModel();
    }

    // Acción GET: Los roles 'Client', 'Employee' y 'Admin' tienen acceso
    [HttpGet]
    public IActionResult Index()
    {
        // No necesitas validar los roles aquí porque todos los usuarios autenticados tienen acceso.
        var productProxy = new ProductProxy();
        var products = productProxy.GetProducts();
        _productViewModel.Products = products;
        return View(_productViewModel);
    }

    // Acción POST: Solo los roles 'Admin' y 'Employee' pueden agregar productos
    [Authorize(Roles = "Admin,Employee")]
    [ValidateAntiForgeryToken]
    [HttpPost]
    public IActionResult Create(Product product)
    {
        var productProxy = new ProductProxy();
        var result = productProxy.Create(product);
        _productViewModel.Error = result == null ? "Producto no pudo ser guardado" : "";
        return RedirectToAction("Index");
    }

    // Acción GET: Solo los roles 'Admin' y 'Employee' pueden gestionar productos

    [HttpGet]
    public IActionResult Search(int productId)
    {
        var productProxy = new ProductProxy();
        var productFound = productProxy.RetrieveById(productId);
        _productViewModel.Products = productProxy.GetProducts();
        _productViewModel.ProductSearch = productFound; // Asignar el producto encontrado
        _productViewModel.Error = productFound == null ? "Product not found" : ""; // Error si el producto no se encuentra

        return View("Index", _productViewModel); // Pasar el modelo a la vista
    }

    [HttpGet]
    [Authorize(Roles = "Admin,Employee")]
    public IActionResult Delete(int id)
    {
        var productProxy = new ProductProxy();
        bool isDeleted = productProxy.Delete(id);
        _productViewModel.Error = isDeleted ? "" : "Product cannot be deleted";

        return RedirectToAction("Index");
    }
    
    [HttpPost]
    [ValidateAntiForgeryToken]
    [Authorize(Roles = "Admin,Employee")]
    public IActionResult Update(Product product) {
        var productProxy = new ProductProxy();
        bool isUpdated = productProxy.Update(product);
        _productViewModel.Error = isUpdated ? "" : "Product cannot be updated";

        return RedirectToAction("Index");
    }
}

WebAppLayer/Controllers/UserController.cs
using Microsoft.AspNetCore.Mvc;
using Entities;
using Microsoft.AspNetCore.Authorization;
using ProxyServiceLayer;
using WebAppLayer.Models;

namespace WebAppLayer.Controllers;

[Authorize]
public class UserController : Controller
{
    private readonly UserViewModel _UserViewModel;

    public UserController()
    {
        _UserViewModel = new UserViewModel();
    }

    // Acción GET: Los roles 'Client', ' y 'Admin' tienen acceso
    [HttpGet]
    public IActionResult Index()
    {
        // No necesitas validar los roles aquí porque todos los usuarios autenticados tienen acceso.
        var UserProxy = new UserProxy();
        var Users = UserProxy.GetUsers();
        _UserViewModel.Users = Users;
        return View(_UserViewModel);
    }

    // Acción POST: Solo los roles 'Admin' y ' pueden agregar Useros
    [Authorize(Roles = "Admin")]
    [HttpPost]
    [ValidateAntiForgeryToken]
    public IActionResult Create(User User)
    {
        var UserProxy = new UserProxy();
        var result = UserProxy.Create(User);
        _UserViewModel.Error = result == null ? "Usero no pudo ser guardado" : "";
        return RedirectToAction("Index");
    }

    // Acción GET: Solo los roles 'Admin' y ' pueden gestionar Useros

    [HttpGet]
    public IActionResult Search(int UserId)
    {
        var UserProxy = new UserProxy();
        var UserFound = UserProxy.RetrieveById(UserId);
        _UserViewModel.Users = UserProxy.GetUsers();
        _UserViewModel.UserSearch = UserFound; // Asignar el User encontrado
        _UserViewModel.Error = UserFound == null ? "User not found" : ""; // Error si el Usero no se encuentra

        return View("Index", _UserViewModel); // Pasar el modelo a la vista
    }

    [HttpGet]
    [Authorize(Roles = "Admin")]
    public IActionResult Delete(int id)
    {
        var UserProxy = new UserProxy();
        bool isDeleted = UserProxy.Delete(id);
        _UserViewModel.Error = isDeleted ? "" : "User cannot be deleted";

        return RedirectToAction("Index");
    }
    
    [HttpPost]
    [ValidateAntiForgeryToken]
    [Authorize(Roles = "Admin")]
    public IActionResult Update(User User) {
        var UserProxy = new UserProxy();
        bool isUpdated = UserProxy.Update(User);
        _UserViewModel.Error = isUpdated ? "" : "User cannot be updated";

        return RedirectToAction("Index");
    }
}

WebAppLayer/Views/Shared/_Layout.cshtml
@using System.Security.Claims
@{
    if (User.Identity == null) return;
    var role = User.FindFirst(ClaimTypes.Role)?.Value;
}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebAppLayer</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebAppLayer.styles.css" asp-append-version="true" />
</head>


<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WebAppLayer</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        @if (role == Roles.Admin)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Index">Users</a>
                            </li>
                        }
                        @if (role == Roles.Admin || role == Roles.Employee || role == Roles.Client)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Product"
                                    asp-action="Index">Products</a>
                            </li>
                        }
                        @if (role == Roles.Admin || role == Roles.Employee)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Category"
                                    asp-action="Index">Categories</a>
                            </li>
                        }
                        <li class="nav-item">
                            <a class="btn btn-light" asp-area="" asp-controller="Account" asp-action="Logout">Logout</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - WebAppLayer - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>

</html>

WebAppLayer/Views/Shared/_LoginLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
</head>
<body>
    <main>
        @RenderBody()
    </main>
</body>
</html>

WebAppLayer/Views/Shared/_NavBar.cshtml
@{
    var role = Context.Session.GetString("Role");
}
<ul class="navbar-nav">
    <li class="nav-item"><a class="nav-link" asp-controller="Admin" asp-action="Index">Home</a></li>
    @if (role == "Admin")
    {
        <li class="nav-item"><a class="nav-link" asp-controller="Admin" asp-action="Index">Admin Panel</a></li>
        <li class="nav-item"><a class="nav-link" asp-controller="Product" asp-action="Create">Create Product</a></li>
        <li class="nav-item"><a class="nav-link" asp-controller="Category" asp-action="Index">Manage Categories</a></li>
    }
    else if (role == "Client")
    {
        <li class="nav-item"><a class="nav-link" asp-controller="Product" asp-action="Index">View Products</a></li>
    }
    else if (role == "Viewer")
    {
        <li class="nav-item"><a class="nav-link" asp-controller="Product" asp-action="Index">View Products</a></li>
    }
</ul>